name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-and-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Npm setup
        run: npm ci

      - name: Lint & types
        run: npm test
